// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://naxlqswlakdmvvjvsicb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5heGxxc3dsYWtkbXZ2anZzaWNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MjcxNzYsImV4cCI6MjA2NzQwMzE3Nn0.7Y7dJsjL552uH6PM0Ht1x05CTkAImUKyzmgpOYamkWM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});